# Generated by Django 2.2.3 on 2021-08-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerQuery',
            fields=[
                ('row_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('row_creation_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_id', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(max_length=1)),
                ('query_description', models.TextField(blank=True, null=True)),
                ('issue_photo_content_dir', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_photo', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_ref1', models.TextField(blank=True, null=True)),
                ('additional_ref2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_uery',
                'managed': True,
            },
        ),
    ]
