# Generated by Django 2.2.3 on 2021-08-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custApp', '0002_auto_20210802_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_query',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
