# Generated by Django 2.2.3 on 2021-08-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custApp', '0003_customer_query_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_query',
            name='user_uploaded_img',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d'),
        ),
    ]
